#!/usr/bin/env python3
"""Plot the small follow-up's two distinct experiments."""
import json
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt


def main():
    groups=json.loads(Path('data/model_eval/followup/summary.json').read_text())['groups']
    plt.rcParams.update({'font.family':'DejaVu Sans','svg.fonttype':'none','svg.hashsalt':'board-followup-v1'})
    fig,axes=plt.subplots(2,1,figsize=(11,8.7));fig.subplots_adjust(left=.32,right=.96,top=.79,bottom=.20,hspace=.65)
    fig.text(.05,.96,'Give communication a purpose; test storage separately',fontsize=17,weight='bold',va='top')
    fig.text(.05,.91,'Real model actions · two fresh task instances per experiment · four decisions per row',fontsize=10,color='#526175')
    palette=[('correct','Correct','#197C80'),('stale','Stale','#D68938'),('other_incorrect','Other / incomplete','#C64B40'),('abstained','Abstained','#CFD6DE'),('operational_stops','Operational stop','#8B5CA6')]
    for ax,experiment,title in zip(axes,['voluntary','required'],['Voluntary: each agent holds a different fragment','Required board read: fixed publishers create a stale overwrite']):
        rows=[g for g in groups if g['experiment']==experiment];left=[0]*len(rows)
        for key,label,color in palette:
            vals=[g['outcomes'].get(key,0) for g in rows];ax.barh(range(len(rows)),vals,left=left,color=color,label=label,height=.65)
            for i,v in enumerate(vals):
                if v:ax.text(left[i]+v/2,i,str(v),ha='center',va='center',color='#182535' if key=='abstained' else 'white',weight='bold')
            left=[a+b for a,b in zip(left,vals)]
        ax.set_yticks(range(len(rows)),[g['model'].split('/')[1]+' · '+g['mode'].replace('_','-') for g in rows],fontsize=9)
        ax.invert_yaxis();ax.set_xlim(0,4);ax.set_xticks(range(5));ax.tick_params(axis='y',length=0)
        ax.set_title(title,loc='left',fontsize=11,pad=12)
        for edge in ['top','right','left']:ax.spines[edge].set_visible(False)
    handles,labels=axes[0].get_legend_handles_labels();fig.legend(handles,labels,loc='lower center',bbox_to_anchor=(.55,.08),ncol=3,frameon=False,fontsize=9)
    fig.text(.05,.025,'All 8 voluntary shared agents published. Required-mode publications were scripted, not generated by models.\nCounts include stopped agents. Tiny dependent samples; no benchmark or population-performance claims.',fontsize=9,color='#526175')
    for extension in ['svg','png']:fig.savefig(f'charts/11-board-adoption-and-storage.{extension}',dpi=160,metadata={'Date':None} if extension=='svg' else None,facecolor='white')
    svg=Path('charts/11-board-adoption-and-storage.svg')
    svg.write_text('\n'.join(line.rstrip() for line in svg.read_text().splitlines())+'\n')
    plt.close(fig)

if __name__=='__main__':main()
